import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex space-x-10">
          <Link href={"/ticket"}>Create a Ticket</Link>
          <Link href={"/tickets"}>Check Current Ticket List</Link>
          <span>drop down to choose roles</span>
        </div>
        {children}
      </body>
    </html>
  );
}
